### ISSUE TITLE
✔️ Deploy Preview for *mrjithin* ready!

### ISSUE THREAD

**Issue by German8cock** [mrjithin/my-portfolio#8]
✔️ Deploy Preview for *mrjithin* ready!

🔨 Explore the source changes: 52d37781d17b54eebb5e18721fd05db83652ea9e

🔍 Inspect the deploy log: [https://app.netlify.com/sites/mrjithin/deploys/6170f46470871b0007bdb752](https://app.netlify.com/sites/mrjithin/deploys/6170f46470871b0007bdb752)

😎 Browse the preview: [https://deploy-preview-7--mrjithin.netlify.app](https://deploy-preview-7--mrjithin.netlify.app)

_Originally posted by @netlify[bot] in https://github.com/mrjithin/my-portfolio/issues/7#issuecomment-948259870_

**Comment by mrjithin** [comment]
Hmmm I didn't quite understand the reason for this issue
